# Generated by Django 3.0.6 on 2020-05-20 16:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('detail', models.CharField(max_length=280)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Pemasukan'), ('2', 'Permintaan')], default='1', max_length=2)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='APD',
            fields=[
                ('modelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kawal.ModelBase')),
            ],
            bases=('kawal.modelbase',),
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('modelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kawal.ModelBase')),
                ('address', models.CharField(max_length=140)),
            ],
            bases=('kawal.modelbase',),
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kawal.Transaction')),
                ('apd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kawal.APD')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kawal.Hospital'),
        ),
    ]
